
version: '3'
services:
  app:
    image: danreynolds/financynerdman:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
      - logs:/app/log/
    env_file:
      - .env
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    networks:
      default:
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  logs:
