# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50bda64ef8ec15679caeb6819a0742af9c91b89fb466bc0f681d9e943c8b99752ce10f0e599e76652c8c233a3b45dcd25a88941a5da9f0619e24cdf08399adcb

test:
  secret_key_base: d29318ffa5800b3000cef4d7f6e90a1d57241d4b069d916d17e0e001e3553134d0e415c04e3a071d8f611c379bb71aa07793bbc2ce6993dc06a297dc79a54fa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
