categories: https://www.nerdwallet.com/blog/wp-json/wp/v2/categories/?search={post_category}
posts_by_category: https://nerdwallet.com/blog/wp-json/nw/v1/posts/?per_page={post_size}&categories={category_slug}&_embed=true
eviews: https://www.nerdwallet.com/blog/wp-json/nw/v1/reviews/?search={search}
tools: https://www.nerdwallet.com/blog/wp-json/nw/v1/tools/{tool_id}/
